// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBByfkuo0Rmxze02Q3a-DzY0KlP75ViZao',
    appId: '1:360258541174:web:eae780e1262a25d2ebb157',
    messagingSenderId: '360258541174',
    projectId: 'zestify-26472',
    authDomain: 'zestify-26472.firebaseapp.com',
    storageBucket: 'zestify-26472.firebasestorage.app',
    measurementId: 'G-6D06CYN3B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwPl5wspFUaxFTTucnfi6uQPNqbdmE1ZU',
    appId: '1:360258541174:android:97be23affe837249ebb157',
    messagingSenderId: '360258541174',
    projectId: 'zestify-26472',
    storageBucket: 'zestify-26472.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL0_pD7zQiT7EEuN8mryZbIXqGfnmiUSs',
    appId: '1:360258541174:ios:93383150d46c2b6aebb157',
    messagingSenderId: '360258541174',
    projectId: 'zestify-26472',
    storageBucket: 'zestify-26472.firebasestorage.app',
    iosBundleId: 'com.example.zestify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL0_pD7zQiT7EEuN8mryZbIXqGfnmiUSs',
    appId: '1:360258541174:ios:93383150d46c2b6aebb157',
    messagingSenderId: '360258541174',
    projectId: 'zestify-26472',
    storageBucket: 'zestify-26472.firebasestorage.app',
    iosBundleId: 'com.example.zestify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBByfkuo0Rmxze02Q3a-DzY0KlP75ViZao',
    appId: '1:360258541174:web:4ce8f9a9d696706aebb157',
    messagingSenderId: '360258541174',
    projectId: 'zestify-26472',
    authDomain: 'zestify-26472.firebaseapp.com',
    storageBucket: 'zestify-26472.firebasestorage.app',
    measurementId: 'G-6X4663N94K',
  );
}
